# Generated by Django 5.1.1 on 2024-09-27 23:50

import django.db.models.deletion
import django.utils.timezone
import exercises.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                (
                    "updated_at",
                    exercises.models.UpdatedAtField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                (
                    "updated_at",
                    exercises.models.UpdatedAtField(default=django.utils.timezone.now),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pr",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reps", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=20)),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                (
                    "updated_at",
                    exercises.models.UpdatedAtField(default=django.utils.timezone.now),
                ),
                (
                    "exercise_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
